# fly.toml file generated for wichtelnng on 2023-02-13T14:26:22+01:00

app = "wichtelnng"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
COM_ROMANBOEHM_WICHTELNNG_MAIL_FROM = "wichtelnng@romanboehm.com"
COM_ROMANBOEHM_WICHTELNNG_DOMAIN = "https://wichtelnng.fly.dev"
OBSERVABILITY_LOKI_ENDPOINT = "https://logs-prod-012.grafana.net/loki/api/v1/push"
OBSERVABILITY_LOKI_USERNAME = "<override-with-fly-secret>"
OBSERVABILITY_LOKI_PASSWORD = "<override-with-fly-secret>"
LOGGING_CONFIG = "classpath:logback-loki.xml"
SPRING_DATASOURCE_URL = "jdbc:postgresql://top2.nearest.of.wichtelnng-db.internal:5432/wichtelnng?sslmode=disable"
SPRING_DATASOURCE_USERNAME = "<override-with-fly-secret>"
SPRING_DATASOURCE_PASSWORD = "<override-with-fly-secret>"
SPRING_MAIL_HOST = "mail.manitu.de"
SPRING_MAIL_PORT = "587"
SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE = "true"
SPRING_MAIL_PASSWORD = "<override-with-fly-secret>"
SPRING_MAIL_USERNAME = "<override-with-fly-secret>"

[metrics]
port = 8081
path = "/actuator/prometheus"

[experimental]
auto_rollback = true

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
