name: build and potentially deploy
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: build with Maven
        run: ./mvnw spring-boot:build-image
      - name: setup flyctl
        # if: startsWith(github.ref, 'refs/tags/')
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: provide secrets for fly.io deployment
        # if: startsWith(github.ref, 'refs/tags/')
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          # "If you must pass secrets within a command line, then enclose them within the proper quoting rules.
          # Secrets often contain special characters that may unintentionally affect your shell.
          # To escape these special characters, use quoting with your environment variables."
          # Cf. https://docs.github.com/en/actions/security-guides/encrypted-secrets.
          SECRETS_SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SECRETS_SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SECRETS_SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
          SECRETS_SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
        run: |
          flyctl secrets set \
            "SPRING_DATASOURCE_PASSWORD=$SECRETS_SPRING_DATASOURCE_PASSWORD" \
            "SPRING_DATASOURCE_USERNAME=$SECRETS_SPRING_DATASOURCE_USERNAME" \
            "SPRING_MAIL_PASSWORD=$SECRETS_SPRING_MAIL_PASSWORD" \
            "SPRING_MAIL_USERNAME=$SECRETS_SPRING_MAIL_USERNAME"
      - name: deploy to fly.io
        # if: startsWith(github.ref, 'refs/tags/')
        run: |
          flyctl deploy \
            --local-only \
            --config fly.toml \
            --image com.romanboehm/wichtelnng:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
