name: build and potentially deploy
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: build with Maven
        run: ./mvnw --batch-mode verify
      - name: provide artifacts for fly.io deployment
        # if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: fly-io-artifacts
          path: |
            target/*.jar
            Dockerfile
            fly.toml
  deploy:
    # if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts for fly.io deployment
        uses: actions/download-artifact@v3
        with:
          name: fly-io-artifacts
      - name: setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: provide secrets for fly.io deployment
        run: |
          flyctl secrets set \
            "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" \
            "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" \
            "SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}" \
            "SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: deploy to fly.io
        run: |
          flyctl deploy \
            --config fly.toml \
            --dockerfile Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
