name: build-and-deploy-if-main
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: build with Maven
        run: ./mvnw --batch-mode verify -Dspring.config.additional-location=src/test/resources/application-it.properties
      - name: setup flyctl
        if: github.ref == 'refs/heads/main'
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: provide secrets for fly.io deployment
        if: github.ref == 'refs/heads/main'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          # Re-declare secrets as env vars to escape special characters.
          # Cf. https://docs.github.com/en/actions/security-guides/encrypted-secrets.
          SECRETS_SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SECRETS_SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SECRETS_SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
          SECRETS_SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
          COM_ROMANBOEHM_WICHTELNNG_OBSERVABILITY_LOKI_ENDPOINT: ${{ secrets.COM_ROMANBOEHM_WICHTELNNG_OBSERVABILITY_LOKI_ENDPOINT }}
        run: |
          flyctl secrets set \
            "SPRING_DATASOURCE_PASSWORD=$SECRETS_SPRING_DATASOURCE_PASSWORD" \
            "SPRING_DATASOURCE_USERNAME=$SECRETS_SPRING_DATASOURCE_USERNAME" \
            "SPRING_MAIL_PASSWORD=$SECRETS_SPRING_MAIL_PASSWORD" \
            "SPRING_MAIL_USERNAME=$SECRETS_SPRING_MAIL_USERNAME" \
            "COM_ROMANBOEHM_WICHTELNNG_OBSERVABILITY_LOKI_ENDPOINT=$COM_ROMANBOEHM_WICHTELNNG_OBSERVABILITY_LOKI_ENDPOINT"
      - name: deploy to fly.io
        if: github.ref == 'refs/heads/main'
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
